version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
clone_depth: 1
init:
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore --verbosity m
build_script:
  - cmd: dotnet pack ./Saquib.Utils.Naming/Saquib.Utils.Naming.csproj -c Release --include-source --include-symbols -o ../artifacts
test_script:
  - cmd: dotnet test ./Saquib.Utils.Naming.Tests/Saquib.Utils.Naming.Tests.csproj
deploy:
  provider: NuGet
  api_key:
    secure: vg0d3t3PR6ry+wZ6KcZKmNO1/5iE/W50QcsphboHFXfKZQxi0BWi8IxfLMs3F93b
  skip_symbols: false
  artifact: /artifacts\/.*\.nupkg/
